# Usage:
#   conda build -c defaults -c conda-forge .
package:
  name: pygdf
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') }}

source:
  path: ../..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - python
    - setuptools
    - numba >0.34
  run:
    - python
    - setuptools
    - libgdf 0.1.0a2.*
    - libgdf_cffi 0.1.0a2.*
    - pandas
    - numba >0.34
test:
  imports:
    - pygdf

about:
  home: http://gpuopenanalytics.com/
  license: Apache
  # license_file: LICENSE
  summary: GPU Dataframe core library
