dist: trusty
sudo: required
language: cpp

branches:
    only:
        - master
env:
  global:
     secure: "EHU4ahNqfqSaT+VQ3cc3MRpHgfIg/K+NUXszlsVzbFgDR43LJD61QavtPMzNM73eVZRzvgRD39yYgHjDF6ZhQ4OpSEGzBiNEzAjKLqnl1JWd7V7/L31OiDsJMwweksrWINoKLPzikr2mOecsWGmRJYcLfYeJZcGlf67PuCN6DI2Un/pYXzblKfU2dVg8bP+HdWrnXTT6u4abnjCU+4kwc+kl9NJzLI1Zk5pSDuLkgRbiF90lImofYh8GfjyUhiz1Hnq+TjKOToLNOLxXMuM6NFxAIsdFfNkklXaz/mhQom3ZYfMlkjwWz/vJ0BKk554bq4mfL71yBzgydvprSppI0qfHtEvVIR2OJy9HnPvOiHdh7aL1qOojC00zjj39PyIx8M61ovpOvJOVD0c2/vBr6Et5JGastULJq2ItzHyP6UNn4oZtinmXV061sNSOepVjEstHMLVytP87cmiMMiBeDncFV/Sl3y5w1l7rGFVn4lNr2XDMl0u+WnDbZ9n57qneAweeoYkS0tBDdcVzfhv6+RJd129NNtgJtk4fWkh387kOeAOPz+uqu6GNFgXRT/zmRI8sttMkyjSBQeKLTGkCDrboqlU1DZ2lyORiQ3P2yOdNeBTkDJFvdntYduHM7tzhTFUOoVaOn0aFK+zE+AwLkw1JJEvi4g1tVI+iKuDZd/Y="

matrix:
  include:
    - env: CUDA=8.0.61-1
    - env: CUDA=9.0.176_384.81
    - env: CUDA=9.1.85_387.26
    - env: CUDA=8.0.61-1 BUILD_CFFI=1 PYTHON=3.6
    - env: CUDA=8.0.61-1 BUILD_CFFI=1 PYTHON=3.5
    - env: CUDA=8.0.61-1 BUILD_CFFI=1 PYTHON=2.7

before_install:
  - source ./travisci/install-cuda-trusty.sh
  # install miniconda
  - travis_retry wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda3/bin:$PATH

install:
  # check
  - nvcc --version
  - conda --version
  # install conda build
  - conda install conda-build anaconda-client --yes
  # install libboost
  - sudo apt-get install libboost-all-dev

script:
  # build ligdf
  - source ./travisci/build_libgdf.sh
  # build libgdf_cffi
  - source ./travisci/build_libgdf_cffi.sh

after_success:
  - source ./travisci/upload.sh
